const GM={piano:'acoustic_grand_piano',guitar:'acoustic_guitar_nylon',bass:'acoustic_bass',strings:'string_ensemble_1'};
const CHAIRS=[{id:'piano',name:'Grand piano',role:'Climb voicing'},{id:'guitar',name:'Nylon guitar',role:'Passing figures'},{id:'bass',name:'Acoustic bass',role:'Walk into V'},{id:'strings',name:'String ensemble',role:'Rise pad'}];
const ROOTS={C:0,G:7,D:2,A:9,E:4,F:5,Bb:10};
const NAMES=['C','C#','D','Eb','E','F','F#','G','Ab','A','Bb','B'];
const RECIPES={'iv-V-Iprep':{major:[{deg:4,qual:'min'},{deg:5,qual:'maj'},{deg:1,qual:'sus'},{deg:5,qual:'dom'}],minor:[{deg:4,qual:'min'},{deg:5,qual:'dom'},{deg:1,qual:'min'},{deg:5,qual:'dom'}]},'ii-IV-V':{major:[{deg:2,qual:'min'},{deg:4,qual:'maj'},{deg:2,qual:'dom'},{deg:5,qual:'dom'}],minor:[{deg:2,qual:'dim'},{deg:4,qual:'min'},{deg:7,qual:'maj'},{deg:5,qual:'dom'}]},'vi-IV-I-V':{major:[{deg:6,qual:'min'},{deg:4,qual:'maj'},{deg:1,qual:'maj'},{deg:5,qual:'dom'}],minor:[{deg:6,qual:'maj'},{deg:4,qual:'min'},{deg:1,qual:'min'},{deg:5,qual:'dom'}]},pedal:{major:[{deg:1,qual:'maj'},{deg:1,qual:'add9'},{deg:1,qual:'sus'},{deg:5,qual:'dom'}],minor:[{deg:1,qual:'min'},{deg:1,qual:'min9'},{deg:1,qual:'sus'},{deg:5,qual:'dom'}]}};
const QUAL={maj:[0,4,7],min:[0,3,7],dom:[0,4,7,10],dim:[0,3,6],sus:[0,5,7],add9:[0,4,7,14],min9:[0,3,7,14]};
const state={ac:null,inst:{},armed:false,playing:false,timers:[]};
function midiToName(m){return NAMES[m%12]+Math.floor(m/12-1);}
function chordFor(bar,key){const rootPc=ROOTS[key];const degMap={1:0,2:2,3:4,4:5,5:7,6:9,7:11};const pc=(rootPc+degMap[bar.deg])%12;const midiRoot=48+pc;const notes=QUAL[bar.qual].map(i=>midiRoot+i);const suffix=bar.qual==='maj'?'':bar.qual==='min'?'m':bar.qual==='dom'?'7':bar.qual;return {notes,label:NAMES[pc]+suffix,bass:midiRoot-12};}
function currentBars(){const key=document.getElementById('key').value;const mode=document.getElementById('mode').value;const recipe=document.getElementById('recipe').value;return RECIPES[recipe][mode].map(b=>chordFor(b,key));}
function renderChairs(){document.getElementById('chairs').innerHTML=CHAIRS.map(c=>`<article class="chair" data-id="${c.id}"><h3>${c.name}</h3><p>${c.role} · FluidR3</p></article>`).join('');}
function renderBars(active=-1){const bars=currentBars();document.getElementById('bars').innerHTML=bars.map((b,i)=>`<li class="${i===active?'active':''}"><span class="n">Bar ${i+1}</span><strong>${b.label}</strong></li>`).join('');}
function setStatus(t){document.getElementById('status').textContent=t;}
async function arm(){setStatus('Opening audio + fetching FluidR3_GM chairs…');state.ac=state.ac||new AudioContext();if(state.ac.state==='suspended')await state.ac.resume();const names=Object.values(GM);const loaded=await Promise.all(names.map(n=>Soundfont.instrument(state.ac,n,{soundfont:'FluidR3_GM',format:'mp3'})));state.inst={piano:loaded[0],guitar:loaded[1],bass:loaded[2],strings:loaded[3]};state.armed=true;document.getElementById('play').disabled=false;document.getElementById('stop').disabled=false;document.querySelectorAll('.chair').forEach(el=>el.classList.add('on'));setStatus('Chairs hot. Four bars of live instruments.');}
function stop(){state.playing=false;state.timers.forEach(clearTimeout);state.timers=[];Object.values(state.inst).forEach(i=>i&&i.stop());renderBars(-1);setStatus(state.armed?'Stopped. Ready to climb again.':'Chairs cold.');}
function play(){if(!state.armed)return;stop();state.playing=true;const bpm=Number(document.getElementById('bpm').value)||96;const beat=60/bpm;const barSec=beat*4;const bars=currentBars();setStatus('Climbing — verse last line into hook.');bars.forEach((bar,i)=>{const t0=i*barSec;state.timers.push(setTimeout(()=>{if(!state.playing)return;renderBars(i);const when=state.ac.currentTime;const dur=barSec*0.92;state.inst.piano.play(midiToName(bar.notes[0]+12),when,{duration:dur,gain:0.55});state.inst.piano.play(midiToName(bar.notes[1]+12),when+0.02,{duration:dur,gain:0.4});state.inst.piano.play(midiToName(bar.notes[2]+12),when+0.03,{duration:dur,gain:0.35});state.inst.guitar.play(midiToName(bar.notes[0]),when+0.05,{duration:dur*0.7,gain:0.35});if(bar.notes[2])state.inst.guitar.play(midiToName(bar.notes[2]),when+beat,{duration:beat*1.4,gain:0.28});state.inst.bass.play(midiToName(bar.bass),when,{duration:dur,gain:0.6});if(i===3)state.inst.bass.play(midiToName(bar.bass+7),when+beat*2,{duration:beat*1.6,gain:0.5});state.inst.strings.play(midiToName(bar.notes[0]+12),when,{duration:dur,gain:0.22+i*0.06});state.inst.strings.play(midiToName(bar.notes[2]+12),when+0.04,{duration:dur,gain:0.18+i*0.05});},t0*1000));});state.timers.push(setTimeout(()=>{if(state.playing){state.playing=false;renderBars(-1);setStatus('Climb complete. Drop the hook.');}},bars.length*barSec*1000+80));}
function bind(){renderChairs();renderBars();['key','mode','recipe'].forEach(id=>document.getElementById(id).addEventListener('change',()=>renderBars()));document.getElementById('arm').addEventListener('click',()=>arm().catch(e=>setStatus(String(e))));document.getElementById('play').addEventListener('click',play);document.getElementById('stop').addEventListener('click',stop);}
bind();
